package util.lixeira;

import interfaces.Principal;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JList;
import javax.swing.table.JTableHeader;

/**
 *
 * @author BIC-Jr Guia de Estilo
 */
public class Agendar extends javax.swing.JDialog {

    private JList<String> wordList;

    /**
     * Creates new form Agendar
     *
     * @param parent
     * @param modal
     */
    public Agendar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        alterarIcone();
        carregarClientes();
    }

    private void alterarIcone() {
        URL url = this.getClass().getResource("/imagens/agendar.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
    }

    private void carregarClientes() {
        // change the editor's document
        new util.lixeira.SearchableJComboBox1(comboBoxCliente);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        painelDadosFora = new javax.swing.JPanel();
        painelDadosDentro = new javax.swing.JPanel();
        rotuloCliente = new javax.swing.JLabel();
        comboBoxCliente = new javax.swing.JComboBox<>();
        botaoPesquisar = new javax.swing.JButton();
        botaoAdicionarCliente = new javax.swing.JButton();
        rotuloData = new javax.swing.JLabel();
        seletorDeData = new com.toedter.calendar.JDateChooser();
        painelTitulo = new javax.swing.JPanel();
        rotuloNovoAgendamento = new javax.swing.JLabel();
        painelBotoes = new javax.swing.JPanel();
        botaoCancelar = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();
        painelServicosAgendadosFora = new javax.swing.JPanel();
        painelServicosAgendadosDentro = new javax.swing.JPanel();
        rotuloServico = new javax.swing.JLabel();
        rotuloProfissional = new javax.swing.JLabel();
        rotuloHorario = new javax.swing.JLabel();
        comboBoxServico = new javax.swing.JComboBox<>();
        comboBoxProfissional = new javax.swing.JComboBox<>();
        comboBoxHorario = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaSevicos = new javax.swing.JTable();
        botaoAdicionarServico = new javax.swing.JButton();
        botaoRemoveServico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Agendamento");
        setMinimumSize(new java.awt.Dimension(700, 550));
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        painelDadosFora.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelDadosDentro.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        rotuloCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rotuloCliente.setText("Cliente:*");

        comboBoxCliente.setEditable(true);
        comboBoxCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Breno Ribeiro Barbosa", "Breno Ribeiro Fernandes", "Bruna Souza Ferreira", "Emily Castro Gomes", "Emily Martins Carvalho", "Lara Silva Costa", "Lucas Araujo Oliveira" }));
        comboBoxCliente.setSelectedItem(null);

        botaoPesquisar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/zoom.png"))); // NOI18N
        botaoPesquisar.setToolTipText("Pesquisar cliente");

        botaoAdicionarCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoAdicionarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        botaoAdicionarCliente.setToolTipText("Adcionar novo cliente");
        botaoAdicionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarClienteActionPerformed(evt);
            }
        });

        rotuloData.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rotuloData.setText("Data:*");

        seletorDeData.setToolTipText("Selecionar data");
        seletorDeData.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        seletorDeData.setMinSelectableDate(new java.util.Date(-62135755095000L));
        seletorDeData.setMinimumSize(new java.awt.Dimension(27, 10));
        seletorDeData.setPreferredSize(new java.awt.Dimension(87, 15));

        javax.swing.GroupLayout painelDadosDentroLayout = new javax.swing.GroupLayout(painelDadosDentro);
        painelDadosDentro.setLayout(painelDadosDentroLayout);
        painelDadosDentroLayout.setHorizontalGroup(
            painelDadosDentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosDentroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rotuloCliente)
                .addGap(7, 7, 7)
                .addComponent(comboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(botaoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(botaoAdicionarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(rotuloData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seletorDeData, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        painelDadosDentroLayout.setVerticalGroup(
            painelDadosDentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosDentroLayout.createSequentialGroup()
                .addGroup(painelDadosDentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rotuloCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPesquisar)
                    .addComponent(botaoAdicionarCliente)
                    .addComponent(rotuloData, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seletorDeData, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        painelDadosFora.add(painelDadosDentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 820, 60));

        jPanel1.add(painelDadosFora, java.awt.BorderLayout.CENTER);

        painelTitulo.setBackground(java.awt.Color.black);

        rotuloNovoAgendamento.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rotuloNovoAgendamento.setForeground(new java.awt.Color(255, 255, 255));
        rotuloNovoAgendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/agendar.png"))); // NOI18N
        rotuloNovoAgendamento.setText("NOVO AGENDAMENTO");
        painelTitulo.add(rotuloNovoAgendamento);

        jPanel1.add(painelTitulo, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        painelBotoes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 17, 10));

        botaoCancelar.setBackground(new java.awt.Color(135, 206, 235));
        botaoCancelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoCancelar.setText("Cancelar");
        botaoCancelar.setContentAreaFilled(false);
        botaoCancelar.setOpaque(true);
        botaoCancelar.setPreferredSize(new java.awt.Dimension(120, 30));
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });
        painelBotoes.add(botaoCancelar);
        botaoCancelar.setOpaque(true);

        botaoSalvar.setBackground(new java.awt.Color(46, 139, 87));
        botaoSalvar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoSalvar.setText("Salvar");
        botaoSalvar.setContentAreaFilled(false);
        botaoSalvar.setOpaque(true);
        botaoSalvar.setPreferredSize(new java.awt.Dimension(120, 30));
        painelBotoes.add(botaoSalvar);
        botaoSalvar.setOpaque(true);

        getContentPane().add(painelBotoes, java.awt.BorderLayout.PAGE_END);

        painelServicosAgendadosFora.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelServicosAgendadosDentro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Serviços Agendados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        painelServicosAgendadosDentro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        rotuloServico.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rotuloServico.setText("Serviço:");

        rotuloProfissional.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rotuloProfissional.setText("Profissional:");

        rotuloHorario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rotuloHorario.setText("Horário:");

        comboBoxServico.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboBoxServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboBoxProfissional.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboBoxProfissional.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboBoxHorario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboBoxHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tabelaSevicos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tabelaSevicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serviço", "Profissional", "Horário"
            }
        ));
        tabelaSevicos.setRowHeight(20);
        tabelaSevicos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaSevicos.getTableHeader().setReorderingAllowed(false);
        tabelaSevicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaSevicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaSevicos);
        JTableHeader cabecalho = tabelaSevicos.getTableHeader();
        cabecalho.setFont(new java.awt.Font("Arial", 0, 14));
        tabelaSevicos.getColumnModel().getColumn(0).setPreferredWidth(250);
        tabelaSevicos.getColumnModel().getColumn(1).setPreferredWidth(250);

        botaoAdicionarServico.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoAdicionarServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/inserirTabela.png"))); // NOI18N
        botaoAdicionarServico.setToolTipText("Adicionar serviço à tabela");

        botaoRemoveServico.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoRemoveServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/removerTabela.png"))); // NOI18N
        botaoRemoveServico.setToolTipText("Remover serviço da tabela");
        botaoRemoveServico.setEnabled(false);

        javax.swing.GroupLayout painelServicosAgendadosDentroLayout = new javax.swing.GroupLayout(painelServicosAgendadosDentro);
        painelServicosAgendadosDentro.setLayout(painelServicosAgendadosDentroLayout);
        painelServicosAgendadosDentroLayout.setHorizontalGroup(
            painelServicosAgendadosDentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelServicosAgendadosDentroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelServicosAgendadosDentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelServicosAgendadosDentroLayout.createSequentialGroup()
                        .addGroup(painelServicosAgendadosDentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rotuloServico)
                            .addComponent(comboBoxServico, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(painelServicosAgendadosDentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rotuloProfissional))
                        .addGap(30, 30, 30)
                        .addGroup(painelServicosAgendadosDentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rotuloHorario)
                            .addComponent(comboBoxHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(painelServicosAgendadosDentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelServicosAgendadosDentroLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(botaoAdicionarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelServicosAgendadosDentroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoRemoveServico, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        painelServicosAgendadosDentroLayout.setVerticalGroup(
            painelServicosAgendadosDentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelServicosAgendadosDentroLayout.createSequentialGroup()
                .addGroup(painelServicosAgendadosDentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotuloServico)
                    .addComponent(rotuloProfissional)
                    .addComponent(rotuloHorario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelServicosAgendadosDentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelServicosAgendadosDentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelServicosAgendadosDentroLayout.createSequentialGroup()
                        .addComponent(botaoAdicionarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoRemoveServico, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 167, Short.MAX_VALUE))
                    .addGroup(painelServicosAgendadosDentroLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        painelServicosAgendadosFora.add(painelServicosAgendadosDentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 820, 360));

        getContentPane().add(painelServicosAgendadosFora, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void tabelaSevicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaSevicosMouseClicked
        botaoRemoveServico.setEnabled(true);
    }//GEN-LAST:event_tabelaSevicosMouseClicked

    private void botaoAdicionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarClienteActionPerformed
        Principal inicioAgenda = new Principal(null);
        ClienteNovo clienteCadastrar = new ClienteNovo(inicioAgenda, true);
        clienteCadastrar.setVisible(true);
        if (clienteCadastrar.getCliente() != null) {
            String nome = clienteCadastrar.getCliente();
        }
        inicioAgenda.dispose();
    }//GEN-LAST:event_botaoAdicionarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            Agendar dialog = new Agendar(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionarCliente;
    private javax.swing.JButton botaoAdicionarServico;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoPesquisar;
    private javax.swing.JButton botaoRemoveServico;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JComboBox<String> comboBoxCliente;
    private javax.swing.JComboBox<String> comboBoxHorario;
    private javax.swing.JComboBox<String> comboBoxProfissional;
    private javax.swing.JComboBox<String> comboBoxServico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelDadosDentro;
    private javax.swing.JPanel painelDadosFora;
    private javax.swing.JPanel painelServicosAgendadosDentro;
    private javax.swing.JPanel painelServicosAgendadosFora;
    private javax.swing.JPanel painelTitulo;
    private javax.swing.JLabel rotuloCliente;
    private javax.swing.JLabel rotuloData;
    private javax.swing.JLabel rotuloHorario;
    private javax.swing.JLabel rotuloNovoAgendamento;
    private javax.swing.JLabel rotuloProfissional;
    private javax.swing.JLabel rotuloServico;
    private com.toedter.calendar.JDateChooser seletorDeData;
    private javax.swing.JTable tabelaSevicos;
    // End of variables declaration//GEN-END:variables
}
