package util.lixeira;

import util.lixeira.Agendar;
import java.awt.Image;
import java.awt.Toolkit;
import java.beans.PropertyChangeEvent;
import java.net.URL;
import java.text.SimpleDateFormat;
import javax.swing.table.JTableHeader;

/**
 * @author BIC-Jr Guia de Estilo
 */
public class InicioAgendaBotoes extends javax.swing.JFrame {

    public InicioAgendaBotoes() {
        initComponents();
        implementarTeclado();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelLestePrincipal = new javax.swing.JPanel();
        painelPagamentos = new javax.swing.JPanel();
        rotuloPagamentosPendentes = new javax.swing.JLabel();
        painelTabela = new javax.swing.JScrollPane();
        tabelaPagamentos = new javax.swing.JTable();
        painelMeioPrincipal = new javax.swing.JPanel();
        painelAgenda = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        calendario = new com.toedter.calendar.JCalendar();
        ano1 = new javax.swing.JLabel();
        semana1 = new javax.swing.JLabel();
        dia1 = new javax.swing.JLabel();
        mes1 = new javax.swing.JLabel();
        semana2 = new javax.swing.JLabel();
        dia2 = new javax.swing.JLabel();
        mes2 = new javax.swing.JLabel();
        ano2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jTextField23 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jTextField27 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jTextField41 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField42 = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jTextField43 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jTextField46 = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField55 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        jTextField56 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField58 = new javax.swing.JTextField();
        jTextField59 = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();
        painelTituloAgenda = new javax.swing.JPanel();
        rotuloAgendamentos = new javax.swing.JLabel();
        painelTopoPrincipal = new javax.swing.JPanel();
        painelBotoes = new javax.swing.JPanel();
        botaoAgendarNovo = new javax.swing.JButton();
        botaoNovoCliente = new javax.swing.JButton();
        botaoPagar = new javax.swing.JButton();
        painelLogo = new javax.swing.JPanel();
        rotuloLogomarca = new javax.swing.JLabel();
        painelBemVindo = new javax.swing.JPanel();
        rotuloBemVindo = new javax.swing.JLabel();
        botaoPreferencias = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        menuBarraPrincipal = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        menuEstoque = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        menuPedidos = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        menuFinancas = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RECANTO BELEZA");
        setMinimumSize(new java.awt.Dimension(1420, 800));

        painelLestePrincipal.setLayout(new java.awt.BorderLayout());

        rotuloPagamentosPendentes.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rotuloPagamentosPendentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/money.png"))); // NOI18N
        rotuloPagamentosPendentes.setText("Pagamentos Pendentes");
        painelPagamentos.add(rotuloPagamentosPendentes);

        painelLestePrincipal.add(painelPagamentos, java.awt.BorderLayout.NORTH);

        painelTabela.setPreferredSize(new java.awt.Dimension(410, 620));

        tabelaPagamentos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tabelaPagamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Deisymar Botega", "R$ 200,00"},
                {"Marcelo Balbino", "R$ 150,00"},
                {"Paula Arthuso", "R$ 100,00"},
                {"Christiano Oliveira", "R$ 80,00"}
            },
            new String [] {
                "Cliente", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPagamentos.setPreferredSize(new java.awt.Dimension(410, 610));
        tabelaPagamentos.setRowHeight(20);
        tabelaPagamentos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaPagamentos.getTableHeader().setReorderingAllowed(false);
        painelTabela.setViewportView(tabelaPagamentos);
        JTableHeader cabecalho = tabelaPagamentos.getTableHeader();
        cabecalho.setFont(new java.awt.Font("Arial", 0, 14));
        tabelaPagamentos.getColumnModel().getColumn(0).setPreferredWidth(300);

        painelLestePrincipal.add(painelTabela, java.awt.BorderLayout.CENTER);

        getContentPane().add(painelLestePrincipal, java.awt.BorderLayout.EAST);

        painelMeioPrincipal.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("09:00");
        painelAgenda.add(jLabel1);
        jLabel1.setBounds(40, 180, 40, 17);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField1.setText("Ana Flávia Carvalhais");
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        painelAgenda.add(jTextField1);
        jTextField1.setBounds(110, 180, 150, 17);

        jTextField2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField2.setText("Matização");
        jTextField2.setBorder(null);
        jTextField2.setMinimumSize(new java.awt.Dimension(63, 17));
        jTextField2.setOpaque(false);
        painelAgenda.add(jTextField2);
        jTextField2.setBounds(270, 180, 140, 17);
        painelAgenda.add(jSeparator1);
        jSeparator1.setBounds(30, 200, 420, 10);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Horário");
        painelAgenda.add(jLabel4);
        jLabel4.setBounds(40, 150, 60, 17);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Cliente");
        painelAgenda.add(jLabel5);
        jLabel5.setBounds(110, 150, 50, 17);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Serviço");
        painelAgenda.add(jLabel6);
        jLabel6.setBounds(270, 150, 70, 17);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField4.setText("André Luiz");
        jTextField4.setBorder(null);
        jTextField4.setOpaque(false);
        painelAgenda.add(jTextField4);
        jTextField4.setBounds(110, 240, 150, 17);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("10:00");
        painelAgenda.add(jLabel2);
        jLabel2.setBounds(40, 240, 40, 17);

        jTextField5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField5.setText("Relaxamento");
        jTextField5.setBorder(null);
        jTextField5.setMinimumSize(new java.awt.Dimension(63, 17));
        jTextField5.setOpaque(false);
        jTextField5.setPreferredSize(new java.awt.Dimension(63, 17));
        painelAgenda.add(jTextField5);
        jTextField5.setBounds(270, 240, 140, 17);
        painelAgenda.add(jSeparator2);
        jSeparator2.setBounds(30, 260, 420, 10);

        jTextField7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField7.setText("Selagem");
        jTextField7.setBorder(null);
        jTextField7.setMinimumSize(new java.awt.Dimension(63, 17));
        jTextField7.setOpaque(false);
        jTextField7.setPreferredSize(new java.awt.Dimension(63, 17));
        painelAgenda.add(jTextField7);
        jTextField7.setBounds(270, 210, 140, 17);

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField8.setText("Ana Flávia Carvalhais");
        jTextField8.setBorder(null);
        jTextField8.setOpaque(false);
        painelAgenda.add(jTextField8);
        jTextField8.setBounds(110, 210, 150, 17);
        painelAgenda.add(jSeparator3);
        jSeparator3.setBounds(30, 230, 420, 10);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("09:30");
        painelAgenda.add(jLabel3);
        jLabel3.setBounds(40, 210, 40, 17);

        calendario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        calendario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        painelAgenda.add(calendario);
        calendario.setBounds(0, 0, 260, 130);

        ano1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        ano1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ano1.setText("ano2");
        painelAgenda.add(ano1);
        ano1.setBounds(270, 40, 60, 40);

        semana1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        semana1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        semana1.setText("semana1");
        painelAgenda.add(semana1);
        semana1.setBounds(350, 10, 80, 30);

        dia1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        dia1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dia1.setText("dia1");
        dia1.setPreferredSize(new java.awt.Dimension(73, 29));
        painelAgenda.add(dia1);
        dia1.setBounds(350, 40, 80, 30);

        mes1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mes1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mes1.setText("mes1");
        painelAgenda.add(mes1);
        mes1.setBounds(330, 70, 120, 30);

        semana2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        semana2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        semana2.setText("semana2");
        painelAgenda.add(semana2);
        semana2.setBounds(810, 20, 90, 30);

        dia2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        dia2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dia2.setText("dia2");
        painelAgenda.add(dia2);
        dia2.setBounds(830, 50, 50, 30);

        mes2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mes2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mes2.setText("mes2");
        painelAgenda.add(mes2);
        mes2.setBounds(800, 80, 110, 30);

        ano2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        ano2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ano2.setText("ano1");
        painelAgenda.add(ano2);
        ano2.setBounds(710, 50, 60, 40);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("10:30");
        painelAgenda.add(jLabel8);
        jLabel8.setBounds(40, 270, 40, 17);

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField10.setText("Felipe Maia");
        jTextField10.setBorder(null);
        jTextField10.setOpaque(false);
        painelAgenda.add(jTextField10);
        jTextField10.setBounds(110, 270, 150, 17);

        jTextField11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField11.setText("Pintura");
        jTextField11.setBorder(null);
        jTextField11.setMinimumSize(new java.awt.Dimension(63, 17));
        jTextField11.setOpaque(false);
        jTextField11.setPreferredSize(new java.awt.Dimension(63, 17));
        painelAgenda.add(jTextField11);
        jTextField11.setBounds(270, 270, 140, 17);
        painelAgenda.add(jSeparator4);
        jSeparator4.setBounds(30, 290, 420, 10);

        jTextField13.setEditable(false);
        jTextField13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField13.setText("Shirley Ane");
        jTextField13.setBorder(null);
        jTextField13.setOpaque(false);
        painelAgenda.add(jTextField13);
        jTextField13.setBounds(110, 300, 150, 17);

        jTextField14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField14.setText("Sobrancelhas");
        jTextField14.setBorder(null);
        jTextField14.setMinimumSize(new java.awt.Dimension(63, 17));
        jTextField14.setOpaque(false);
        jTextField14.setPreferredSize(new java.awt.Dimension(63, 17));
        painelAgenda.add(jTextField14);
        jTextField14.setBounds(270, 300, 140, 17);
        painelAgenda.add(jSeparator5);
        jSeparator5.setBounds(30, 320, 420, 10);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("11:00");
        painelAgenda.add(jLabel9);
        jLabel9.setBounds(40, 300, 40, 17);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("11:30");
        painelAgenda.add(jLabel10);
        jLabel10.setBounds(40, 330, 40, 17);

        jTextField17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField17.setText("Pintura");
        jTextField17.setBorder(null);
        jTextField17.setMinimumSize(new java.awt.Dimension(63, 17));
        jTextField17.setOpaque(false);
        jTextField17.setPreferredSize(new java.awt.Dimension(63, 17));
        painelAgenda.add(jTextField17);
        jTextField17.setBounds(270, 330, 140, 17);
        painelAgenda.add(jSeparator6);
        jSeparator6.setBounds(30, 350, 420, 10);

        jTextField18.setEditable(false);
        jTextField18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField18.setText("Guilherme César");
        jTextField18.setBorder(null);
        jTextField18.setOpaque(false);
        painelAgenda.add(jTextField18);
        jTextField18.setBounds(110, 330, 150, 17);

        jTextField19.setEditable(false);
        jTextField19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField19.setText("Valeska Valgas");
        jTextField19.setBorder(null);
        jTextField19.setOpaque(false);
        painelAgenda.add(jTextField19);
        jTextField19.setBounds(110, 360, 150, 17);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("12:00");
        painelAgenda.add(jLabel11);
        jLabel11.setBounds(40, 360, 40, 17);
        painelAgenda.add(jSeparator7);
        jSeparator7.setBounds(30, 380, 420, 10);

        jTextField21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField21.setText("Manicure");
        jTextField21.setBorder(null);
        jTextField21.setMinimumSize(new java.awt.Dimension(63, 17));
        jTextField21.setOpaque(false);
        jTextField21.setPreferredSize(new java.awt.Dimension(63, 17));
        painelAgenda.add(jTextField21);
        jTextField21.setBounds(270, 360, 140, 17);

        jTextField22.setEditable(false);
        jTextField22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField22.setText("Mateus Morais");
        jTextField22.setBorder(null);
        jTextField22.setOpaque(false);
        painelAgenda.add(jTextField22);
        jTextField22.setBounds(110, 390, 150, 17);
        painelAgenda.add(jSeparator8);
        jSeparator8.setBounds(30, 410, 420, 10);

        jTextField23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField23.setText("Corte");
        jTextField23.setBorder(null);
        jTextField23.setMinimumSize(new java.awt.Dimension(63, 17));
        jTextField23.setOpaque(false);
        jTextField23.setPreferredSize(new java.awt.Dimension(63, 17));
        painelAgenda.add(jTextField23);
        jTextField23.setBounds(270, 390, 140, 17);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("12:30");
        painelAgenda.add(jLabel12);
        jLabel12.setBounds(40, 390, 40, 17);

        jTextField26.setEditable(false);
        jTextField26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField26.setText("Ana Carolina Campos");
        jTextField26.setBorder(null);
        jTextField26.setOpaque(false);
        painelAgenda.add(jTextField26);
        jTextField26.setBounds(110, 420, 150, 17);
        painelAgenda.add(jSeparator9);
        jSeparator9.setBounds(30, 440, 420, 10);

        jTextField27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField27.setText("Maquiagem");
        jTextField27.setBorder(null);
        jTextField27.setMinimumSize(new java.awt.Dimension(63, 17));
        jTextField27.setOpaque(false);
        jTextField27.setPreferredSize(new java.awt.Dimension(63, 17));
        painelAgenda.add(jTextField27);
        jTextField27.setBounds(270, 420, 140, 17);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("13:00");
        painelAgenda.add(jLabel13);
        jLabel13.setBounds(40, 420, 40, 17);

        jTextField29.setEditable(false);
        jTextField29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField29.setText("Gabriel Alves");
        jTextField29.setBorder(null);
        jTextField29.setOpaque(false);
        painelAgenda.add(jTextField29);
        jTextField29.setBounds(610, 240, 150, 17);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("14:30");
        painelAgenda.add(jLabel14);
        jLabel14.setBounds(540, 240, 40, 17);
        painelAgenda.add(jSeparator10);
        jSeparator10.setBounds(530, 260, 420, 10);

        jTextField30.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField30.setText("Massagem");
        jTextField30.setBorder(null);
        jTextField30.setMinimumSize(new java.awt.Dimension(63, 17));
        jTextField30.setOpaque(false);
        jTextField30.setPreferredSize(new java.awt.Dimension(63, 17));
        painelAgenda.add(jTextField30);
        jTextField30.setBounds(770, 240, 140, 17);

        jTextField31.setEditable(false);
        jTextField31.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField31.setText("Luana Oliveira");
        jTextField31.setBorder(null);
        jTextField31.setOpaque(false);
        painelAgenda.add(jTextField31);
        jTextField31.setBounds(610, 330, 150, 17);
        painelAgenda.add(jSeparator11);
        jSeparator11.setBounds(530, 290, 420, 10);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("15:00");
        painelAgenda.add(jLabel15);
        jLabel15.setBounds(540, 270, 40, 17);

        jTextField33.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField33.setText("Visagismo");
        jTextField33.setBorder(null);
        jTextField33.setMinimumSize(new java.awt.Dimension(63, 17));
        jTextField33.setOpaque(false);
        jTextField33.setPreferredSize(new java.awt.Dimension(63, 17));
        painelAgenda.add(jTextField33);
        jTextField33.setBounds(770, 270, 140, 17);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("15:30");
        painelAgenda.add(jLabel16);
        jLabel16.setBounds(540, 300, 40, 17);

        jTextField35.setEditable(false);
        jTextField35.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField35.setText("Renata Martins");
        jTextField35.setBorder(null);
        jTextField35.setOpaque(false);
        painelAgenda.add(jTextField35);
        jTextField35.setBounds(610, 270, 150, 17);

        jTextField36.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField36.setText("Spa das Mãos");
        jTextField36.setBorder(null);
        jTextField36.setMinimumSize(new java.awt.Dimension(63, 17));
        jTextField36.setOpaque(false);
        jTextField36.setPreferredSize(new java.awt.Dimension(63, 17));
        painelAgenda.add(jTextField36);
        jTextField36.setBounds(770, 300, 140, 17);
        painelAgenda.add(jSeparator12);
        jSeparator12.setBounds(530, 320, 420, 10);

        jTextField37.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField37.setText("Micropigmentação");
        jTextField37.setBorder(null);
        jTextField37.setMinimumSize(new java.awt.Dimension(63, 17));
        jTextField37.setOpaque(false);
        jTextField37.setPreferredSize(new java.awt.Dimension(63, 17));
        painelAgenda.add(jTextField37);
        jTextField37.setBounds(770, 330, 140, 17);

        jTextField38.setEditable(false);
        jTextField38.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField38.setText("Gabriel Scotá");
        jTextField38.setBorder(null);
        jTextField38.setOpaque(false);
        painelAgenda.add(jTextField38);
        jTextField38.setBounds(610, 300, 150, 17);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("16:00");
        painelAgenda.add(jLabel17);
        jLabel17.setBounds(540, 330, 40, 17);
        painelAgenda.add(jSeparator13);
        jSeparator13.setBounds(530, 350, 420, 10);

        jTextField41.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField41.setText("Tonalização");
        jTextField41.setBorder(null);
        jTextField41.setMinimumSize(new java.awt.Dimension(63, 17));
        jTextField41.setOpaque(false);
        jTextField41.setPreferredSize(new java.awt.Dimension(63, 17));
        painelAgenda.add(jTextField41);
        jTextField41.setBounds(770, 360, 140, 17);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("16:30");
        painelAgenda.add(jLabel18);
        jLabel18.setBounds(540, 360, 40, 17);

        jTextField42.setEditable(false);
        jTextField42.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField42.setText("Raíssa Franco");
        jTextField42.setBorder(null);
        jTextField42.setOpaque(false);
        painelAgenda.add(jTextField42);
        jTextField42.setBounds(610, 360, 150, 17);
        painelAgenda.add(jSeparator14);
        jSeparator14.setBounds(530, 380, 420, 10);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setText("17:00");
        painelAgenda.add(jLabel19);
        jLabel19.setBounds(540, 390, 40, 17);

        jTextField43.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField43.setText("Alisamento");
        jTextField43.setBorder(null);
        jTextField43.setMinimumSize(new java.awt.Dimension(63, 17));
        jTextField43.setOpaque(false);
        jTextField43.setPreferredSize(new java.awt.Dimension(63, 17));
        painelAgenda.add(jTextField43);
        jTextField43.setBounds(770, 390, 140, 17);

        jTextField44.setEditable(false);
        jTextField44.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField44.setText("Filipe Argentino");
        jTextField44.setBorder(null);
        jTextField44.setOpaque(false);
        painelAgenda.add(jTextField44);
        jTextField44.setBounds(610, 390, 150, 17);
        painelAgenda.add(jSeparator15);
        jSeparator15.setBounds(530, 410, 420, 10);

        jTextField46.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField46.setText("Arranjo Cabelo");
        jTextField46.setBorder(null);
        jTextField46.setMinimumSize(new java.awt.Dimension(63, 17));
        jTextField46.setOpaque(false);
        jTextField46.setPreferredSize(new java.awt.Dimension(63, 17));
        painelAgenda.add(jTextField46);
        jTextField46.setBounds(770, 420, 140, 17);

        jTextField47.setEditable(false);
        jTextField47.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField47.setText("Sara Saldanha");
        jTextField47.setBorder(null);
        jTextField47.setOpaque(false);
        painelAgenda.add(jTextField47);
        jTextField47.setBounds(610, 420, 150, 17);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setText("17:30");
        painelAgenda.add(jLabel20);
        jLabel20.setBounds(540, 420, 40, 17);
        painelAgenda.add(jSeparator16);
        jSeparator16.setBounds(530, 440, 420, 10);

        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setText("Serviço");
        painelAgenda.add(jLabel24);
        jLabel24.setBounds(770, 150, 130, 17);

        jLabel25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel25.setText("Cliente");
        painelAgenda.add(jLabel25);
        jLabel25.setBounds(610, 150, 50, 17);

        jLabel26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel26.setText("Horário");
        painelAgenda.add(jLabel26);
        jLabel26.setBounds(540, 150, 60, 17);

        jTextField55.setEditable(false);
        jTextField55.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField55.setText("Hortência Sena");
        jTextField55.setBorder(null);
        jTextField55.setOpaque(false);
        painelAgenda.add(jTextField55);
        jTextField55.setBounds(610, 180, 150, 17);

        jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel27.setText("13:30");
        painelAgenda.add(jLabel27);
        jLabel27.setBounds(540, 180, 40, 17);
        painelAgenda.add(jSeparator19);
        jSeparator19.setBounds(530, 200, 420, 10);

        jTextField56.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField56.setText("Pedicure");
        jTextField56.setBorder(null);
        jTextField56.setMinimumSize(new java.awt.Dimension(63, 17));
        jTextField56.setOpaque(false);
        jTextField56.setPreferredSize(new java.awt.Dimension(63, 17));
        painelAgenda.add(jTextField56);
        jTextField56.setBounds(770, 180, 140, 17);

        jLabel28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel28.setText("14:00");
        painelAgenda.add(jLabel28);
        jLabel28.setBounds(540, 210, 40, 17);

        jTextField58.setEditable(false);
        jTextField58.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField58.setText("Patrick Oliveira");
        jTextField58.setBorder(null);
        jTextField58.setOpaque(false);
        painelAgenda.add(jTextField58);
        jTextField58.setBounds(610, 210, 150, 17);

        jTextField59.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField59.setText("Spa dos Pés");
        jTextField59.setBorder(null);
        jTextField59.setMinimumSize(new java.awt.Dimension(63, 17));
        jTextField59.setOpaque(false);
        jTextField59.setPreferredSize(new java.awt.Dimension(63, 17));
        painelAgenda.add(jTextField59);
        jTextField59.setBounds(770, 210, 140, 17);
        painelAgenda.add(jSeparator20);
        jSeparator20.setBounds(530, 230, 420, 10);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eye.png"))); // NOI18N
        jButton1.setToolTipText("Ver detalhes");
        painelAgenda.add(jButton1);
        jButton1.setBounds(410, 390, 30, 20);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eye.png"))); // NOI18N
        jButton2.setToolTipText("Ver detalhes");
        painelAgenda.add(jButton2);
        jButton2.setBounds(410, 180, 30, 20);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eye.png"))); // NOI18N
        jButton3.setToolTipText("Ver detalhes");
        painelAgenda.add(jButton3);
        jButton3.setBounds(410, 210, 30, 20);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eye.png"))); // NOI18N
        jButton4.setToolTipText("Ver detalhes");
        painelAgenda.add(jButton4);
        jButton4.setBounds(410, 240, 30, 20);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eye.png"))); // NOI18N
        jButton5.setToolTipText("Ver detalhes");
        painelAgenda.add(jButton5);
        jButton5.setBounds(410, 270, 30, 20);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eye.png"))); // NOI18N
        jButton6.setToolTipText("Ver detalhes");
        painelAgenda.add(jButton6);
        jButton6.setBounds(410, 300, 30, 20);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eye.png"))); // NOI18N
        jButton7.setToolTipText("Ver detalhes");
        painelAgenda.add(jButton7);
        jButton7.setBounds(410, 330, 30, 20);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eye.png"))); // NOI18N
        jButton8.setToolTipText("Ver detalhes");
        painelAgenda.add(jButton8);
        jButton8.setBounds(410, 360, 30, 20);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eye.png"))); // NOI18N
        jButton9.setToolTipText("Ver detalhes");
        painelAgenda.add(jButton9);
        jButton9.setBounds(910, 180, 30, 20);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eye.png"))); // NOI18N
        jButton10.setToolTipText("Ver detalhes");
        painelAgenda.add(jButton10);
        jButton10.setBounds(410, 420, 30, 20);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eye.png"))); // NOI18N
        jButton11.setToolTipText("Ver detalhes");
        painelAgenda.add(jButton11);
        jButton11.setBounds(910, 210, 30, 20);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eye.png"))); // NOI18N
        jButton12.setToolTipText("Ver detalhes");
        painelAgenda.add(jButton12);
        jButton12.setBounds(910, 240, 30, 20);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eye.png"))); // NOI18N
        jButton13.setToolTipText("Ver detalhes");
        painelAgenda.add(jButton13);
        jButton13.setBounds(910, 270, 30, 20);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eye.png"))); // NOI18N
        jButton14.setToolTipText("Ver detalhes");
        painelAgenda.add(jButton14);
        jButton14.setBounds(910, 300, 30, 20);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eye.png"))); // NOI18N
        jButton15.setToolTipText("Ver detalhes");
        painelAgenda.add(jButton15);
        jButton15.setBounds(910, 330, 30, 20);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eye.png"))); // NOI18N
        jButton16.setToolTipText("Ver detalhes");
        painelAgenda.add(jButton16);
        jButton16.setBounds(910, 360, 30, 20);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eye.png"))); // NOI18N
        jButton17.setToolTipText("Ver detalhes");
        painelAgenda.add(jButton17);
        jButton17.setBounds(910, 390, 30, 20);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eye.png"))); // NOI18N
        jButton18.setToolTipText("Ver detalhes");
        painelAgenda.add(jButton18);
        jButton18.setBounds(910, 420, 30, 20);

        fundo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/agenda.png"))); // NOI18N
        fundo.setMaximumSize(new java.awt.Dimension(1260, 650));
        fundo.setMinimumSize(new java.awt.Dimension(1260, 650));
        fundo.setPreferredSize(new java.awt.Dimension(1260, 650));
        painelAgenda.add(fundo);
        fundo.setBounds(0, 0, 990, 640);

        painelMeioPrincipal.add(painelAgenda, java.awt.BorderLayout.CENTER);

        rotuloAgendamentos.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rotuloAgendamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/date.png"))); // NOI18N
        rotuloAgendamentos.setText("Agendamentos");
        painelTituloAgenda.add(rotuloAgendamentos);

        painelMeioPrincipal.add(painelTituloAgenda, java.awt.BorderLayout.NORTH);

        getContentPane().add(painelMeioPrincipal, java.awt.BorderLayout.CENTER);

        painelTopoPrincipal.setLayout(new java.awt.BorderLayout());

        botaoAgendarNovo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoAgendarNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/agendar.png"))); // NOI18N
        botaoAgendarNovo.setMnemonic('a');
        botaoAgendarNovo.setText("Agendar");
        botaoAgendarNovo.setToolTipText("Registrar novo agendamento");
        botaoAgendarNovo.setContentAreaFilled(false);
        botaoAgendarNovo.setNextFocusableComponent(botaoNovoCliente);
        botaoAgendarNovo.setPreferredSize(new java.awt.Dimension(200, 60));
        botaoAgendarNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoAgendarNovoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoAgendarNovoMouseExited(evt);
            }
        });
        botaoAgendarNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAgendarNovoActionPerformed(evt);
            }
        });
        painelBotoes.add(botaoAgendarNovo);

        botaoNovoCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoNovoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarioNovo.png"))); // NOI18N
        botaoNovoCliente.setMnemonic('n');
        botaoNovoCliente.setText("Novo Cliente");
        botaoNovoCliente.setToolTipText("Registrar novo cliente");
        botaoNovoCliente.setContentAreaFilled(false);
        botaoNovoCliente.setName(""); // NOI18N
        botaoNovoCliente.setNextFocusableComponent(botaoPagar);
        botaoNovoCliente.setOpaque(true);
        botaoNovoCliente.setPreferredSize(new java.awt.Dimension(200, 60));
        botaoNovoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoNovoClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoNovoClienteMouseExited(evt);
            }
        });
        botaoNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoClienteActionPerformed(evt);
            }
        });
        painelBotoes.add(botaoNovoCliente);

        botaoPagar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pagar.png"))); // NOI18N
        botaoPagar.setMnemonic('p');
        botaoPagar.setText("Pagar");
        botaoPagar.setToolTipText("Registrar pagamento");
        botaoPagar.setContentAreaFilled(false);
        botaoPagar.setNextFocusableComponent(botaoPreferencias);
        botaoPagar.setOpaque(true);
        botaoPagar.setPreferredSize(new java.awt.Dimension(200, 60));
        botaoPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoPagarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoPagarMouseExited(evt);
            }
        });
        painelBotoes.add(botaoPagar);

        painelTopoPrincipal.add(painelBotoes, java.awt.BorderLayout.CENTER);

        painelLogo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        rotuloLogomarca.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        rotuloLogomarca.setForeground(new java.awt.Color(139, 71, 137));
        rotuloLogomarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoSalao.png"))); // NOI18N
        rotuloLogomarca.setText("<html><body>RECANTO<br>BELEZA</body></html>");
        painelLogo.add(rotuloLogomarca);

        painelTopoPrincipal.add(painelLogo, java.awt.BorderLayout.WEST);

        painelBemVindo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        rotuloBemVindo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rotuloBemVindo.setText("Bem-vinda, Fulana!");
        painelBemVindo.add(rotuloBemVindo);

        botaoPreferencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/settings.png"))); // NOI18N
        botaoPreferencias.setToolTipText("Preferências");
        botaoPreferencias.setContentAreaFilled(false);
        botaoPreferencias.setNextFocusableComponent(botaoSair);
        botaoPreferencias.setOpaque(true);
        botaoPreferencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoPreferenciasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoPreferenciasMouseExited(evt);
            }
        });
        painelBemVindo.add(botaoPreferencias);

        botaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        botaoSair.setToolTipText("Sair");
        botaoSair.setContentAreaFilled(false);
        botaoSair.setNextFocusableComponent(calendario);
        botaoSair.setOpaque(true);
        botaoSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoSairMouseExited(evt);
            }
        });
        painelBemVindo.add(botaoSair);

        painelTopoPrincipal.add(painelBemVindo, java.awt.BorderLayout.EAST);

        getContentPane().add(painelTopoPrincipal, java.awt.BorderLayout.NORTH);

        menuBarraPrincipal.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        menuCadastros.setMnemonic('c');
        menuCadastros.setText("Cadastros");

        jMenuItem1.setMnemonic('c');
        jMenuItem1.setText("Clientes");
        menuCadastros.add(jMenuItem1);

        jMenuItem2.setMnemonic('p');
        jMenuItem2.setText("Produtos");
        menuCadastros.add(jMenuItem2);

        jMenuItem3.setMnemonic('u');
        jMenuItem3.setText("Usuários");
        menuCadastros.add(jMenuItem3);

        jMenuItem4.setMnemonic('f');
        jMenuItem4.setText("Fornecedores");
        menuCadastros.add(jMenuItem4);

        jMenuItem20.setText("Serviços");
        menuCadastros.add(jMenuItem20);

        jMenuItem21.setText("Profissionais");
        menuCadastros.add(jMenuItem21);

        menuBarraPrincipal.add(menuCadastros);

        menuEstoque.setMnemonic('e');
        menuEstoque.setText("Estoque");

        jMenuItem17.setMnemonic('p');
        jMenuItem17.setText("Produtos");
        menuEstoque.add(jMenuItem17);

        jMenuItem18.setMnemonic('c');
        jMenuItem18.setText("Consultar");
        menuEstoque.add(jMenuItem18);

        menuBarraPrincipal.add(menuEstoque);

        menuPedidos.setMnemonic('d');
        menuPedidos.setText("Pedidos");

        jMenuItem9.setMnemonic('p');
        jMenuItem9.setText("Pedidos Realizados");
        menuPedidos.add(jMenuItem9);

        jMenuItem19.setMnemonic('v');
        jMenuItem19.setText("Vendas");
        menuPedidos.add(jMenuItem19);

        menuBarraPrincipal.add(menuPedidos);

        menuFinancas.setMnemonic('f');
        menuFinancas.setText("Finanças");

        jMenuItem10.setMnemonic('f');
        jMenuItem10.setText("Gerenciador Financeiro");
        menuFinancas.add(jMenuItem10);

        jMenuItem11.setMnemonic('r');
        jMenuItem11.setText("Contas a Receber");
        menuFinancas.add(jMenuItem11);

        jMenuItem12.setMnemonic('p');
        jMenuItem12.setText("Contas a Pagar");
        menuFinancas.add(jMenuItem12);

        menuBarraPrincipal.add(menuFinancas);

        menuRelatorios.setMnemonic('r');
        menuRelatorios.setText("Relatórios");

        jMenuItem13.setMnemonic('c');
        jMenuItem13.setText("Relatório de Cliente Inadimplentes");
        menuRelatorios.add(jMenuItem13);

        jMenuItem14.setMnemonic('e');
        jMenuItem14.setText("Relatório de Estoque");
        menuRelatorios.add(jMenuItem14);

        jMenuItem15.setMnemonic('f');
        jMenuItem15.setText("Relatório de Fornecedores");
        menuRelatorios.add(jMenuItem15);

        jMenuItem16.setMnemonic('l');
        jMenuItem16.setText("Relatório de Lucros e Despesas");
        menuRelatorios.add(jMenuItem16);

        menuBarraPrincipal.add(menuRelatorios);

        menuAjuda.setMnemonic('u');
        menuAjuda.setText("Ajuda");

        jMenuItem5.setMnemonic('d');
        jMenuItem5.setText("Documentação");
        menuAjuda.add(jMenuItem5);

        jMenuItem6.setMnemonic('u');
        jMenuItem6.setText("Suporte");
        menuAjuda.add(jMenuItem6);

        jMenuItem7.setMnemonic('t');
        jMenuItem7.setText("Atalhos");
        menuAjuda.add(jMenuItem7);

        jMenuItem8.setMnemonic('o');
        jMenuItem8.setText("Sobre");
        menuAjuda.add(jMenuItem8);

        menuBarraPrincipal.add(menuAjuda);

        setJMenuBar(menuBarraPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoClienteActionPerformed
        ClienteNovo clienteCadastrar = new ClienteNovo(this, true);
        clienteCadastrar.setVisible(true);
    }//GEN-LAST:event_botaoNovoClienteActionPerformed

    private void botaoAgendarNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAgendarNovoActionPerformed
        Agendar agendar = new Agendar(this, true);
        agendar.setVisible(true);
    }//GEN-LAST:event_botaoAgendarNovoActionPerformed

    private void botaoAgendarNovoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAgendarNovoMouseExited
        botaoAgendarNovo.setOpaque(false);
        botaoAgendarNovo.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_botaoAgendarNovoMouseExited

    private void botaoNovoClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoNovoClienteMouseEntered
        botaoNovoCliente.setOpaque(true);
        botaoNovoCliente.setBackground(new java.awt.Color(135, 206, 235));
    }//GEN-LAST:event_botaoNovoClienteMouseEntered

    private void botaoNovoClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoNovoClienteMouseExited
        botaoNovoCliente.setOpaque(false);
        botaoNovoCliente.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_botaoNovoClienteMouseExited

    private void botaoPagarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoPagarMouseEntered
        botaoPagar.setOpaque(true);
        botaoPagar.setBackground(new java.awt.Color(135, 206, 235));
    }//GEN-LAST:event_botaoPagarMouseEntered

    private void botaoPagarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoPagarMouseExited
        botaoPagar.setOpaque(true);
        botaoPagar.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_botaoPagarMouseExited

    private void botaoPreferenciasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoPreferenciasMouseEntered
        botaoPreferencias.setOpaque(true);
        botaoPreferencias.setBackground(new java.awt.Color(135, 206, 235));
    }//GEN-LAST:event_botaoPreferenciasMouseEntered

    private void botaoPreferenciasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoPreferenciasMouseExited
        botaoPreferencias.setOpaque(true);
        botaoPreferencias.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_botaoPreferenciasMouseExited

    private void botaoSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSairMouseEntered
        botaoSair.setOpaque(true);
        botaoSair.setBackground(new java.awt.Color(135, 206, 235));
    }//GEN-LAST:event_botaoSairMouseEntered

    private void botaoAgendarNovoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAgendarNovoMouseEntered
        botaoAgendarNovo.setOpaque(true);
        botaoAgendarNovo.setBackground(new java.awt.Color(135, 206, 235));
    }//GEN-LAST:event_botaoAgendarNovoMouseEntered

    private void botaoSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSairMouseExited
        botaoSair.setOpaque(true);
        botaoSair.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_botaoSairMouseExited
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioAgendaBotoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InicioAgendaBotoes().setVisible(true);
        });
    }

    private void implementarTeclado() {
        URL url = this.getClass().getResource("/imagens/logoSalao.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
        mudarDayChooser();
        calendarioMudar();

    }

    private void mudarDayChooser() {
        calendario.getDayChooser().addPropertyChangeListener("day", (PropertyChangeEvent e) -> {
            calendarioMudar();
        });

        calendario.getMonthChooser().addPropertyChangeListener("month", (PropertyChangeEvent e) -> {
            calendarioMudar();
        });

        calendario.getYearChooser().addPropertyChangeListener("year", (PropertyChangeEvent e) -> {
            calendarioMudar();
        });
    }

    private void calendarioMudar() {
        dia1.setText(new SimpleDateFormat("d").format(calendario.getDate()));
        dia2.setText(new SimpleDateFormat("d").format(calendario.getDate()));
        mes1.setText(new SimpleDateFormat("MMMM").format(calendario.getDate()));
        mes2.setText(new SimpleDateFormat("MMMM").format(calendario.getDate()));
        ano1.setText(new SimpleDateFormat("yyyy").format(calendario.getDate()));
        ano2.setText(new SimpleDateFormat("yyyy").format(calendario.getDate()));
        semana1.setText(new SimpleDateFormat("EEEE").format(calendario.getDate()).replaceAll("-feira", ""));
        semana2.setText(new SimpleDateFormat("EEEE").format(calendario.getDate()).replace("-feira", ""));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ano1;
    private javax.swing.JLabel ano2;
    private javax.swing.JButton botaoAgendarNovo;
    private javax.swing.JButton botaoNovoCliente;
    private javax.swing.JButton botaoPagar;
    private javax.swing.JButton botaoPreferencias;
    private javax.swing.JButton botaoSair;
    private com.toedter.calendar.JCalendar calendario;
    private javax.swing.JLabel dia1;
    private javax.swing.JLabel dia2;
    private javax.swing.JLabel fundo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField jTextField56;
    private javax.swing.JTextField jTextField58;
    private javax.swing.JTextField jTextField59;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenuBar menuBarraPrincipal;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenu menuEstoque;
    private javax.swing.JMenu menuFinancas;
    private javax.swing.JMenu menuPedidos;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JLabel mes1;
    private javax.swing.JLabel mes2;
    private javax.swing.JLayeredPane painelAgenda;
    private javax.swing.JPanel painelBemVindo;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelLestePrincipal;
    private javax.swing.JPanel painelLogo;
    private javax.swing.JPanel painelMeioPrincipal;
    private javax.swing.JPanel painelPagamentos;
    private javax.swing.JScrollPane painelTabela;
    private javax.swing.JPanel painelTituloAgenda;
    private javax.swing.JPanel painelTopoPrincipal;
    private javax.swing.JLabel rotuloAgendamentos;
    private javax.swing.JLabel rotuloBemVindo;
    private javax.swing.JLabel rotuloLogomarca;
    private javax.swing.JLabel rotuloPagamentosPendentes;
    private javax.swing.JLabel semana1;
    private javax.swing.JLabel semana2;
    private javax.swing.JTable tabelaPagamentos;
    // End of variables declaration//GEN-END:variables
}
